# The following properties are required for tiho (productive) deployment.
# For productive deployment, all properties must be configured or enabled.
# Only relevant properties should be listed here; otherwise, they should be deleted.
# Unless otherwise specified, empty properties are relevant and must be configured.
# Temporary disabled properties require further configuration or other dependencies.

##############################################################################
# Basic                                                                      #
##############################################################################
# Configure base url, e.g. http://domain:port, without '/'. Temporary disabled to use default.
#MCR.baseurl=
# Requires MCR.baseurl, therefore temporary disabled.
#MIR.CanonicalBaseURL=%MCR.baseurl%/

MCR.NameOfProject=tiho
MIR.projectid.default=tiho

##############################################################################
# Access Control                                                             #
##############################################################################
# Also allow submitter to search after all objects.
MIR.OwnerStrategy.AllowedRolesForSearch=admin,editor,submitter

MIR.Access.Strategy.Classifications=mir_access,state

##############################################################################
# Frontend                                                                   #
##############################################################################
MIR.CustomLayout.JS=tiho.js

# Disable shariff buttons.
MIR.shariff=hide

##############################################################################
# Editor                                                                     #
##############################################################################
# Customization of XEditor forms.
MIR.EditorForms.CustomIncludes=%MIR.EditorForms.CustomIncludes%,xslStyle:editor/mir2xeditor:webapp:editor/editor-customization.xed

##############################################################################
# MIR Citation                                                               #
##############################################################################
# Override citation styles.
MIR.citationStyles=american-chemical-society,american-medical-association,apa,chicago-author-date,council-of-science-editors-author-date,din-1505-2,iso690-author-date-de,dependent/national-library-of-medicine
MIR.defaultCitationStyle=din-1505-2

##############################################################################
# Batch Editor                                                               #
##############################################################################
MCR.BatchEditor.BaseLevel.object=/mycoreobject
MCR.BatchEditor.BaseLevel.publication=/mycoreobject/metadata/def.modsContainer/modsContainer/mods:mods
MCR.BatchEditor.BaseLevel.servflags=/mycoreobject/service

MCR.BatchEditor.place.Path2Remove=mods:originInfo/mods:place[mods:placeTerm/text()="{0}"]
MCR.BatchEditor.place.Path2Add=mods:originInfo/mods:place[mods:placeTerm/text()="{0}"]="{0}"

MCR.BatchEditor.publisher.Path2Remove=mods:originInfo/mods:publisher[text()="{0}"]
MCR.BatchEditor.publisher.Path2Add=mods:originInfo/mods:publisher[text()="{0}"]="{0}"

MCR.BatchEditor.toBeDisplayedIn.Path2Remove=mods:classification[contains(@authorityURI,"/toBeDisplayedIn")][@valueURI="https://elib.tiho-hannover.de/api/v1/classifications/toBeDisplayedIn#{0}"]
MCR.BatchEditor.toBeDisplayedIn.Path2Add=mods:classification[@authorityURI="https://elib.tiho-hannover.de/api/v1/classifications/toBeDisplayedIn"][@displayLabel="toBeDisplayedIn"][@valueURI="https://elib.tiho-hannover.de/api/v1/classifications/toBeDisplayedIn#{0}"]

MCR.BatchEditor.publicationIndex.Path2Remove=mods:classification[contains(@authorityURI,"/publicationIndex")][@valueURI="https://elib.tiho-hannover.de/api/v1/classifications/publicationIndex#{0}"]
MCR.BatchEditor.publicationIndex.Path2Add=mods:classification[@authorityURI="https://elib.tiho-hannover.de/api/v1/classifications/publicationIndex"][@displayLabel="publicationIndex"][@valueURI="https://elib.tiho-hannover.de/api/v1/classifications/publicationIndex#{0}"]

MCR.BatchEditor.state.Path2Remove=servstates/servstate[@classid="state"][@categid="{0}"]
MCR.BatchEditor.state.Path2Add=servstates[@class="MCRMetaClassification"]/servstate[@inherited="0"][@classid="state"][@categid="{0}"]

##############################################################################
# OAI Data Provider                                                          #
##############################################################################
MCR.OAIDataProvider.OAI2.RepositoryName=eLib der Stiftung Tier\u00E4rztliche Hochschule Hannover
MCR.OAIDataProvider.OAI2.RepositoryIdentifier=%MCR.baseurl%
MCR.OAIDataProvider.OAI2.AdminEmail=
MCR.OAIDataProvider.OAI2.RecordSampleID=etd_mods_00000055
MCR.OAIDataProvider.RepositoryPublisherName=Stiftung Tier\u00E4rztliche Hochschule Hannover
MCR.OAIDataProvider.RepositoryPublisherPlace=Hannover
MCR.OAIDataProvider.RepositoryPublisherAddress=Haus 262, 30559 Hannover

# Restrict result to published mods.
MCR.OAIDataProvider.OAI2.Search.Restriction=objectType:mods AND (state:published OR state:deleted OR state:blocked)

# Define XMetaDissPlus set.
MCR.OAIDataProvider.OAI2.Sets.doc-type.URI=xslStyle:classification2sets:classification:metadata:2:children:diniPublType2022
MCR.OAIDataProvider.OAI2.Sets.doc-type.Classification=diniPublType2022
MCR.OAIDataProvider.OAI2.Sets.xmetadissplus.Query=derCount:[1 TO *] AND NOT(mods.type:video OR mods.type:research_data) AND state:published AND objectType:mods AND mods.identifier:urn* AND mods.identifier:*95-* AND mods.identifier:*gbv*
MCR.OAIDataProvider.OAI2.Sets.xmetadissplus.URI=webapp:oai/set_xmetadissplus.xml

# Define URN set.
MCR.OAIDataProvider.OAI2.Sets.urn.Query=mods.identifier:urn* AND mods.identifier:*95-* AND mods.identifier:*gbv*
MCR.OAIDataProvider.OAI2.Sets.urn=webapp:oai/set_urn.xml

# Define set for long term archiving.
MCR.OAIDataProvider.OAI2.Sets.lza.URI=webapp:oai/set_lza.xml
MCR.OAIDataProvider.OAI2.Sets.lza.Query=objectType:mods AND state:published AND derCount:[1 TO *]

# Set metadata formats.
MCR.OAIDataProvider.OAI2.MetadataFormats=oai_dc,mods,epicur,xMetaDissPlus

# Define set specifications.
MCR.OAIDataProvider.OAI2.Sets=doc-type,open_access,openaire,driver,ec_fundedresources,GENRE,ddc,xmetadissplus,lza,urn

# Set friendly OAI interfaces.
MCR.OAIDataProvider.OAI2.Friends.OpenAgrar=https://www.openagrar.de/servlets/OAIDataProvider
MCR.OAIDataProvider.OAI2.Friends.DuEPublico=http://duepublico.uni-duisburg-essen.de/servlets/OAIDataProvider
MCR.OAIDataProvider.OAI2.Friends.DBThueringen=http://www.db-thueringen.de/servlets/OAIDataProvider
MCR.OAIDataProvider.OAI2.Friends.RosDok=http://rosdok.uni-rostock.de/oai

##############################################################################
# ePuSta                                                                     #
##############################################################################
# ePuSta endpoint is required, therefore temporarily disabled.
#MIR.ePuSta=show
MIR.ePuSta.providerURL=

##############################################################################
# URN configuration                                                          #
##############################################################################
MCR.URN.Resolver.MasterURL=https://nbn-resolving.org/

MCR.PI.MetadataService.MODSURN.Prefix=urn:nbn:de:gbv:95-
MCR.PI.Service.DNBURN.Generator=TIHOGenerator
MCR.PI.Generator.TIHOGenerator=de.gbv.reposis.tiho.TIHOGenerator

##############################################################################
# XMetaDissPlus                                                              #
##############################################################################
MIR.xMetaDissPlus.diniPublType.classificationId=diniPublType2022
MIR.dc.diniPublType.classificationId=diniPublType2022
MIR.dc.ignoredClassificationIds=diniPublType

##############################################################################
# Sitelinks                                                                  #
##############################################################################
# Active Sitelinks servlet.
MCR.Servlet.SitelinksServlet.Disabled=false

##############################################################################
# Misc                                                                       #
##############################################################################
# Persists transient user when creating an object, e.g. Shibboleth users.
MCR.EventHandler.MCRObject.110.Class=org.mycore.user2.events.MCRPersistTransientUserEventHandler

MCR.Servlet.MCRPropertyHelperContentServlet.Disabled=true
